# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
    push:
        branches: ["v2.3"]
    pull_request:
        branches: ["v2.3"]

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Setup repo
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Setup Deno
              # uses: denoland/setup-deno@v1
              uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31 # v1.1.2
              with:
                  deno-version: v1.x

            # Uncomment this step to verify the use of 'deno fmt' on each commit.
            # - name: Verify formatting
            #   run: deno fmt --check

            - name: Pre build civet and pre-install
              run: |
                  npm install
                  npm run build

            # TODO: correct linting
            - name: Run linter
              run: |
                  deno lint src/
                  deno lint test/
                  deno lint example/

            #
            - name: Run tests
              run: |
                  deno test --unstable --allow-all test/deno/test.mjs

    publish-npm:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - run: npm publish --access public --tag alpha
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
